#!/usr/bin/env bash
cd ASKALYED
echo -e "\e[33m        _     ____   _   _     _    _______\e[0m"
echo -e "\e[33m       / \   / ___| | |/ /    / \  / ____|\e[0m"
echo -e "\e[33m      / _ \  \ ___\ | ' /    / _ \ |  _|\e[0m"
echo -e "\e[33m     / ___ \  ___)  | . \   / ___ \| |___\e[0m"
echo -e "\e[33m    /_/   \_\|____/ \_|\_\ /_/   \_\_____|\e[0m"
while(true) do
lua start.lua 
done